# Generated by Django 5.0.4 on 2025-02-18 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('FN', 'Furniture'), ('SO', 'Sofas/Seating'), ('KD', 'Kitchen/Dining'), ('LB', 'Living/Bedroom'), ('OL', 'Outdoor Living'), ('HD', 'Home Decor'), ('HA', 'Home Appliances'), ('EL', 'Electronics'), ('LL', 'Lamps/Lighting'), ('TV', 'TV/Audio/vedio'), ('AS', 'Air Solutions'), ('CM', 'Computing/Mobile'), ('OF', 'Office furniture'), ('SP', 'Stool&Pouffes'), ('SF', 'Sofas'), ('CH', 'Chairs'), ('TB', 'Tables'), ('WD', 'Wardrobes'), ('BE', 'Beds'), ('SR', 'Shoe Racks'), ('CS', 'Cabinets & Sideboards'), ('SS', 'Sectional Sofas'), ('RC', 'Recliners'), ('BS', 'Book Shelves'), ('OT', 'Ottomans'), ('CS', 'Cabinets & Sideboards')], max_length=10),
        ),
    ]
