# Generated by Django 5.0.4 on 2025-03-12 10:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_orderitem_order_alter_orderitem_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('FN', 'Furniture'), ('SO', 'Sofas/Seating'), ('KD', 'Kitchen/Dining'), ('LB', 'Living/Bedroom'), ('OL', 'Outdoor Living'), ('HD', 'Home Decor'), ('HA', 'Home Appliances'), ('EL', 'Electronics'), ('LG', 'Lamps/Lighting'), ('TV', 'TV/Audio/vedio'), ('AS', 'Air Solutions'), ('CM', 'Computing/Mobile'), ('OF', 'Office furniture'), ('SP', 'Stool&Pouffes'), ('SF', 'Sofas'), ('CH', 'Chairs'), ('TB', 'Tables'), ('WD', 'Wardrobes'), ('BE', 'Beds'), ('SR', 'Shoe Racks'), ('CS', 'Cabinets & Sideboards'), ('SS', 'Sectional Sofas'), ('RC', 'Recliners'), ('BS', 'Book Shelves'), ('OT', 'Ottomans'), ('SU', 'Sofa Cum Beds'), ('RC', 'Recliner Sets'), ('FT', 'Futons'), ('CL', 'Chaise Loungers'), ('SC', 'Sofa Chairs'), ('SB', 'Settees & Benches'), ('OC', 'Office Chairs'), ('GC', 'Gaming Chairs'), ('OS', 'Outdoor Seating'), ('DT', 'Dining Tables'), ('DB', 'Dining Benches'), ('BF', 'Bar Furniture'), ('DC', 'Dining Chairs'), ('CU', 'Crockery Units'), ('DT', 'Dining Table Sets'), ('ST', 'Serving Trolley'), ('BW', 'Barware'), ('MT', 'Mattresses'), ('DM', 'Dresser Mirrors'), ('CD', 'Chest of Drawers'), ('WS', 'Wall Shelves'), ('BS', 'Bed Side Tables'), ('SD', 'Study Desk'), ('OH', 'Occasional Chairs'), ('BC', 'Book Case & Cabinates'), ('BH', 'Benches'), ('OD', 'Outdoor Dining Sets'), ('GF', 'Garden Furniture Sets'), ('OB', 'Outdoor Storage Boxe'), ('OK', 'Outdoor Kitchens & Bars'), ('AH', 'Adirondack Chairs'), ('ST', 'Spiritual'), ('WC', 'Wall Decor'), ('DM', 'Mirrors'), ('WP', 'Wall Art and Paintings'), ('WS', 'Wall Shelves'), ('PP', 'Pots and Planters Showpieces'), ('VS', 'Vases'), ('OD', 'Outdoor Decor'), ('WH', 'Wall Hangings'), ('CB', 'Collectibles'), ('PF', 'Photo Frames'), ('HF', 'Home Fragrances'), ('JK', 'Jharokhas'), ('FD', 'Festive Decor'), ('DW', 'Dishwasher'), ('RG', 'Refrigerators'), ('WP', 'Water Purifiers'), ('MO', 'Microwave Ovens'), ('LN', 'Laundry'), ('MX', 'Mixer'), ('EI', 'Electric Iron'), ('IN', 'Indection'), ('WM', 'Washing Machines'), ('TV', 'TVs'), ('AP', 'Air Purifiers'), ('AC', 'Air Conditioners'), ('FL', 'Floor Lamps'), ('TL', 'Table Lamps'), ('CL', 'Ceiling Lights'), ('NL', 'Night Lamps'), ('WL', 'Wall Lights'), ('LS', 'Lamp Shades'), ('WSL', 'Work and Study Lamps'), ('OL', 'Outdoor Lights'), ('DL', 'Decorative Lights'), ('BU', 'Bulbs'), ('EL', 'Emergency Lights'), ('KL', 'Kids Lamps'), ('TVS', 'TV & Soundbars'), ('STV', 'webOS for Smart TV'), ('LS', 'Lifestyle Screens'), ('AU', 'Audio'), ('PJ', 'Projectors'), ('CO', 'Cooler'), ('FA', 'Fan'), ('TB', 'Table Fan'), ('MB', 'Mobile'), ('MN', 'Moniters'), ('LP', 'Laptop'), ('KB', 'Keyboard'), ('MO', 'Mouse')], max_length=10),
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'product')},
            },
        ),
    ]
